name: UNICODE check for all htm* files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Browse through all htm* files and see if they can be converted
    - uses: actions/checkout@v4
    - name: Check all files are OK wrt encoding    
      run: |
        all_files_OK=0
        for file_to_check in $(git ls-files '*.htm*')
        do echo Processing $file_to_check
        iconv -f utf-8 -t utf-8 -c $file_to_check > /dev/null
        echo $?
        if [ $? -eq 0 ]
        then  echo OK
        else
        echo NOK
        all_files_OK=1
        fi
        done
        test $all_files_OK == 0